const options = {
  defaultExpandHolderPosition: 'right',
  backgroundImageNoRepeat: true,
  moveToCenterWhenRefresh: false,
  zoomToFitWhenRefresh: false,
  defaultNodeBorderWidth: 0,
  defaultNodeWidth: 80,
  defaultNodeHeight: 80,
  defaultLineColor: 'rgba(255, 140, 0, 1)',
  defaultNodeColor: 'rgba(21, 91, 212, 1)',
  allowShowMiniToolBar: false,
  defaultLineMarker: {
    markerWidth: 15,
    markerHeight: 15,
    refX: 7,
    refY: 7,
    data: 'M 14 7 L 1 .3 L 4 7 L .4 13 L 14 7, Z',
  },
  layouts: [
    {
      layoutName: 'force',
      maxLayoutTimes: 300,
      force_node_repulsion: 1,
      force_line_elastic: 1,
    },
  ],
};
const optionsOne = {
  layouts: [
    {
      label: '中心',
      layoutName: 'tree',
      layoutClassName: 'seeks-layout-center',
      defaultJunctionPoint: 'border',
      defaultNodeShape: 0,
      defaultLineShape: 1,
      from: 'left',
      min_per_width: undefined,
      max_per_width: 200,
      min_per_height: 40,
      max_per_height: undefined,
      levelDistance: '',
    },
  ],
  defaultLineMarker: {
    // markerWidth: 12,
    // markerHeight: 12,
    // refX: -10,
    // refY: 6,
    data: '200, 300, 400, 500, 500, 500, 500',
  },
  moveToCenterWhenRefresh: false,
  // zoomToFitWhenRefresh: false,
  defaultExpandHolderPosition: 'right',
  defaultNodeShape: 1,
  // 宽度
  // defaultNodeWidth: 200,
  defaultLineShape: 4,
  defaultJunctionPoint: 'lr',
  defaultNodeBorderWidth: 0,
  defaultNodeHeight: 40,
  defaultPolyLineRadius: 15,
  defaultLineColor: 'rgba(21, 91, 212, 0.8)',
  defaultNodeColor: 'rgba(21, 91, 212, 0.8)',
  defaultLineTextOffset_x: -8,
  defaultLineTextOffset_y: -1,
};
const optionsTwo = {
  debug: false,
  // lineUseTextPath: true,
  // layouts: [
  //   {
  //     label: 'Tree',
  //     layoutName: 'tree',
  //     from: 'left',
  //     min_per_width: undefined,
  //     max_per_width: 200,
  //     min_per_height: 40,
  //     max_per_height: undefined,
  //     levelDistance: '',
  //   },
  // ],
  // defaultExpandHolderPosition: 'right',
  // defaultNodeShape: 1,
  // // defaultNodeWidth: 100,
  // defaultLineShape: 4,
  // defaultJunctionPoint: 'lr',
  // defaultNodeBorderWidth: 0,
  // defaultNodeHeight: 40,
  // defaultPolyLineRadius: 15,
  // defaultLineColor: 'rgba(21, 91, 212, 0.8)',
  // defaultNodeColor: 'rgba(21, 91, 212, 0.8)',
  // defaultLineMarker: {
  //   data: '200, 300, 400, 500, 500, 500, 500',
  // },

  defaultNodeBorderWidth: 0,
  defaultNodeShape: 1,
  layout: {
    layoutName: 'tree',
    centerOffset_x: 0,
    centerOffset_y: 0,
    distance_coefficient: 1,
    layoutDirection: 'h',
    from: 'left',
    levelDistance: '',
    min_per_width: undefined,
    max_per_width: 200,
    min_per_height: 40,
    max_per_height: undefined,
  },
};

export { options, optionsOne, optionsTwo }