// 审批流程类型枚举，需要注意，code需要与 流程定义code相同
export enum BpmBusinessProcessTypeEnum {
  MODEL_SINGLE_APPROVAL = 'MODEL_SINGLE_APPROVAL', //模块库一级审签
  MODEL_DUAL_APPROVAL = 'MODEL_DUAL_APPROVAL', //模块库二级审签
  KNOWLEDGE_SINGLE_APPROVAL = 'KNOWLEDGE_SINGLE_APPROVAL', //知识库库一级审签
  KNOWLEDGE_DUAL_APPROVAL = 'KNOWLEDGE_DUAL_APPROVAL', //知识库二级审签
  DEFAULT = 'DEFAULT', //通用兜底的界面
  SALE_OPS = 'SALE_OPS', //销售特征审签
  TEC_OPS = 'TEC_OPS', //技术特征审签
  REGIONAL_SALES_RELEASE = 'REGIONAL_SALES_RELEASE', //区域销售发布审签
  REGIONAL_SALES_DISCONTINUED = 'REGIONAL_SALES_DISCONTINUED', //“区域销售特征停售审签
  CONFIG_RULE_CHANGE = 'CONFIG_RULE_CHANGE', //配置规则变更签审流程
  ORDER_MBOM = 'ORDER_MBOM', //订单Mbom发布审签
  PRODUCT_MODEL_RELEASE = 'PRODUCT_MODEL_RELEASE', //产品型号发布流程
  PRODUCT_MODEL_FINALIZATION_RELEASE = 'PRODUCT_MODEL_FINALIZATION_RELEASE', //新产品型号发布流程 --2025年8月13日添加
  PRODUCT_MODEL_CHANGE = 'PRODUCT_MODEL_CHANGE', //产品型号变更流程
  PRODUCT_MODEL_FINALIZATION_CHANGE = 'PRODUCT_MODEL_FINALIZATION_CHANGE', //新产品型号变更流程  -- 2025年8月13日添加
  SALE_OPS_CHANGE = 'SALE_OPS_CHANGE', //销售特征变更审签
  TEC_OPS_CHANGE = 'TEC_OPS_CHANGE', //技术特征变更审签

  ORDER_CONFIG_PROCESS = 'ORDER_CONFIG_PROCESS', //营销点单流程
  FORWARD_DATA_FAIL = 'FORWARD_DATA_FAIL', //转发数据失败流程
  REGIONAL_SALES_CHANGE = 'REGIONAL_SALES_CHANGE', //区域销售配置表变更审签
  STANDARD_BOM_RE = 'STANDARD_BOM_RE', //标配BOM重发审签单

  TASK_OWNER_NOTICE = 'TASK_OWNER_NOTICE', //通知流程

  REGIONAL_SALES_RELEASE_TEM = 'REGIONAL_SALES_RELEASE_TEM', //区域上市批量发送流程
  STANDARD_PROCESSROUTE_RE = 'STANDARD_PROCESSROUTE_RE', //标准工艺路线重发审签单
}

// 根据流程状态判断销售策划、技术配置编辑状态枚举
export enum ProcessProgressTypeEnum {
  DESIGN = 'DESIGN', //设计中
  DRAFT = 'DRAFT', //编制中
  SALES_CONFIRMATION = 'SALES_CONFIRMATION', //销售审批
  SCHEME_CENTER_REVIEW = 'SCHEME_CENTER_REVIEW', //方案中心审批
  NTERNATIONAL_HQ = 'NTERNATIONAL_HQ', //国际总部审批
  TECHNICAL_SUPERVISOR = 'TECHNICAL_SUPERVISOR', //主机厂技术主管审
  DIRECTOR_CONFIRMATION = 'DIRECTOR_CONFIRMATION', //主机厂所长审批
}
