export type CombinationRow = Record<string, string | number | undefined>;

export const combinationLists: Record<number, CombinationRow[]> = {
  1:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        2:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        3:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        4:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        5:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        6:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        7:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        8:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '交流配电组合',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        9:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 7,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        10:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        11:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        12:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        13:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        14:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '取力装置',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        15:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压电池',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        16:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        17:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源OBC',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        18:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        19:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        20:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '柴油发电机组',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        21:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 6,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        22:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        23:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 5,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '整流电源(OBC)',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
        24:[
        {
          p0: 1,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '底盘高压直流电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 2,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '电源机柜',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 3,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '高压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
        {
          p0: 4,
          cellParameterId0: '',
          cellParentNum0: '',
          cellInputOrOutput0: '1',
          cellInputName0:'',
          p1: '低压配电',
          cellParameterId1: '',
          cellParentNum1: '',
          cellInputOrOutput1: '1',
          cellInputName1:'',
          p2: '',
          cellParameterId2: '',
          cellParentNum2: '',
          cellInputOrOutput2: '1',
          cellInputName2:'',
        },
      ],
};
