export interface AnsysParameterItem {
  inputOrOutput?: string;
  ifSingleLine?: string;
  inputType?: string;
  parameterNum?: string;
  parameterId?: string;
  defaultValue?: string;
  pageId?: string;
  inputName?: string;
  id?: string | number;
  tableMap?: {
    colNums: number;
    rowData: Record<string, unknown>[];
  };
}

export function createDefaultAnsysParameterList(pageId = ''): AnsysParameterItem[] {
  return [
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_TYPE',
      parameterId: '',
      defaultValue: 'PLANE183',
      pageId,
      inputName: '模型类型',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_THICK',
      parameterId: '',
      defaultValue: '0.5',
      pageId,
      inputName: '厚度',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MATERIAL_EX',
      parameterId: '',
      defaultValue: '30e6',
      pageId,
      inputName: '弹性模量',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MATERIAL_PREXY',
      parameterId: '',
      defaultValue: '0.27',
      pageId,
      inputName: '泊松比',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_L',
      parameterId: '',
      defaultValue: '6',
      pageId,
      inputName: '横板长度',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_W',
      parameterId: '',
      defaultValue: '2',
      pageId,
      inputName: '宽度',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_L1',
      parameterId: '',
      defaultValue: '2',
      pageId,
      inputName: '竖板长度',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_R1',
      parameterId: '',
      defaultValue: '0.4',
      pageId,
      inputName: '内倒角半径',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_R',
      parameterId: '',
      defaultValue: '0.4',
      pageId,
      inputName: '圆孔半径',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_MODEL_MESSSIZE',
      parameterId: '',
      defaultValue: '0.5',
      pageId,
      inputName: '网格边长',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_TYPE',
      parameterId: '',
      defaultValue: '0',
      pageId,
      inputName: '分析类型',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_FIXPOS',
      parameterId: '',
      defaultValue: 'C1:左上圆孔',
      pageId,
      inputName: '固定位置',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_PRESSPOS1',
      parameterId: '',
      defaultValue: 'L7:右下圆孔左下圆弧',
      pageId,
      inputName: '加力位置1',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_PRESSPOS1_S',
      parameterId: '',
      defaultValue: '50',
      pageId,
      inputName: '加力大小-开始',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_PRESSPOS1_E',
      parameterId: '',
      defaultValue: '500',
      pageId,
      inputName: '加力大小-结束',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_PRESSPOS2',
      parameterId: '',
      defaultValue: 'L8:右下圆孔右下圆弧',
      pageId,
      inputName: '加力位置2',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_PRESSPOS2_S',
      parameterId: '',
      defaultValue: '500',
      pageId,
      inputName: '加力大小-开始',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_PRESSPOS2_E',
      parameterId: '',
      defaultValue: '50',
      pageId,
      inputName: '加力大小-结束',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_RESULT_PIC1',
      parameterId: '',
      defaultValue: '',
      pageId,
      inputName: '分析结果图片1',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_RESULT_PIC2',
      parameterId: '',
      defaultValue: '',
      pageId,
      inputName: '分析结果图片2',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_ANALYSIS_RESULT_PIC3',
      parameterId: '',
      defaultValue: '',
      pageId,
      inputName: '分析结果图片3',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_TEMPLATEFILE',
      parameterId: '',
      defaultValue: '',
      pageId,
      inputName: '模板文件名',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'ANSYS_WB_OUTPUTDIR',
      parameterId: '',
      defaultValue: '',
      pageId,
      inputName: '输出目录',
    },
  ];
}
