server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    client_max_body_size 20000M;
    charset utf-8;

    root   /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ @router;
        index  index.html index.htm;
    }


    location /Api {
        add_header 'Access-Control-Allow-Origin' '*';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://epc-gateway:48080;
        rewrite             ^/Api/(.*)$ /$1 break;
}
  location /doc {
        add_header 'Access-Control-Allow-Origin' '*';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://epc-gateway:48080;
    }
  location /iconify {
        proxy_pass http://10.0.72.11:3000;
        rewrite             ^/iconify/(.*)$ /$1 break;

    }
    #location /system/ {
  #      add_header 'Access-Control-Allow-Origin' '*';
  #      proxy_set_header Host $host;
  #      proxy_set_header X-Real-IP $remote_addr;
  #      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #      proxy_pass http://new-framework-gateway:48080/admin-api/system/;
   # }
    #location /doInit/ {
    #        add_header 'Access-Control-Allow-Origin' '*';
    #        proxy_set_header Host $host;
     #       proxy_set_header X-Real-IP $remote_addr;
      #      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       #     proxy_pass http://new-framework-gateway:48080/;
        #}
    #location /clearCache/ {
     #           add_header 'Access-Control-Allow-Origin' '*';
      #          proxy_set_header Host $host;
       #         proxy_set_header X-Real-IP $remote_addr;
        #        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         #       proxy_pass http://new-framework-gateway:48080/;
          #  }
    error_page   500 502 503 504  /50x.html;


    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
