export function langValue(lang: any, langtype: any) {
  let str = '';
  // 中文
  const arrzhCN = [
    {
      'deng-lu': '登录',
      tenantName: '租户名称',
      username: '用户名',
      password: '密码',
      phoneNumber: '手机号码',
      phoneCode: '手机验证码',
      verificationCode: '验证码',
      rulesusername: '请填写用户名',
      rulespassword: '请填写密码',
      'zheng-zai-jia-zai-xi-tong-zhong': '正在加载系统中...',
      rulesphonenumber: '请输入正确的手机号码',
      Integratedaccount: '集成账号，禁止登录',
      Usernamecannotempty: '用户名称不能为空',
      phonenumberempty: '手机号码不能为空',
      Sendverificationcode: '发送验证码',
      Verificamobile: '手机验证',
      Verificationcodesentsuccessfully: '验证码发送成功',
      Verificationcodesenterrorfully: '验证码发送失败',
      forgotpassword: '忘记密码?',
      Resendinseconds: '秒后重新发送',
      ElectronicCatalogPublishingSystem: '机械设备快速设计系统',
      Welcometologin: '欢迎登录',
      Customersatisfaction: '客户满意',
      Itisourmission: '是我们的宗旨',
      'Responsibility/Communication/Inclusiveness': '责任/沟通/包容',
      Retrievepassword: '找回密码',
      Pleaseenteryourphonenumber: '请输入手机号码',
      Pleaseentertheverificationcode: '请输入验证码',
      Volveraenviardespuésdesegundos: '秒后重新发送',
      Password: '新密码',
      Confirmpassword: '确认密码',
      Thenewpasswordcannotbeempty: '新密码不能为空',
      Confirmpasswordcannotbeempty: '确认密码不能为空',
      Modifiedsuccessfully: '修改成功',
      Thepasswordenteredtwicemustbeconsistent: '两次输入的密码必须一致',
      sure: '确定',
      Cancelación: '取消',
      PasswordPrompt:
        '密码必须包含4种形式文字:大写字母、小写字母、数字和特殊字符:密码中不能包含:连续的字母、数字或键盘符号、重复的字母或数字、工号、OA账号、名字全拼、姓名首字母缩写、电话号码:生日等常见密码或默认密码。',
    },
  ];
  // 英语
  const arrenus = [
    {
      'deng-lu': 'Sign in',
      tenantName: 'tenant name',
      username: 'username',
      password: 'password',
      phoneNumber: 'phoneNumber',
      phoneCode: 'phone Code',
      verificationCode: 'Verification Code',
      rulesusername: 'Please fill in your username',
      rulespassword: 'Please fill in the password',
      'zheng-zai-jia-zai-xi-tong-zhong': 'Loading system...',
      rulesphonenumber: 'Please enter the correct phone number',
      Integratedaccount: 'Integrated account, login prohibited',
      Usernamecannotempty: 'User name cannot be empty',
      phonenumberempty: 'Mobile phone number cannot be empty',
      Sendverificationcode: 'Sendverificationcode',
      Verificamobile: 'Verifica mobile',
      Verificationcodesentsuccessfully: 'Verification code sent successfully',
      Verificationcodesenterrorfully: 'Verification code sending failed',
      forgotpassword: 'forgot password?',
      Resendinseconds: 'Resend in seconds',
      ElectronicCatalogPublishingSystem: ' Parts Electronic Catalog System',
      Welcometologin: 'Welcome to login',
      Customersatisfaction: 'Customer satisfaction',
      Itisourmission: 'It is our mission',
      'Responsibility/Communication/Inclusiveness': 'Responsibility/Communication/Inclusiveness',
      Retrievepassword: 'Retrieve password',
      Pleaseenteryourphonenumber: 'Please enter your phone number',
      Pleaseentertheverificationcode: 'Please enter the verification code',
      Volveraenviardespuésdesegundos: 'Resend in seconds',
      Password: 'Password',
      Confirmpassword: 'Confirm password',
      Thenewpasswordcannotbeempty: 'The new password cannot be empty',
      Confirmpasswordcannotbeempty: 'Confirm password cannot be empty',
      Modifiedsuccessfully: 'Modified successfully',
      Thepasswordenteredtwicemustbeconsistent: 'The password entered twice must be consistent',
      sure: 'sure',
      Cancelación: 'cancel',
      PasswordPrompt:
        'The password must contain four forms of text: uppercase letters, lowercase letters, numbers, and special characters. The password cannot contain consecutive letters, numbers, or keyboard symbols, repeated letters or numbers, employee ID, OA account, full spelling name, initials, phone number, birthday, and other common or default passwords.',
    },
  ];
  // 俄语
  const arrruRU = [
    {
      'deng-lu': 'Регистрация',
      tenantName: 'Имя арендатора',
      username: 'Имя пользователя',
      password: 'Пароль',
      phoneNumber: 'Номер мобильного телефона',
      phoneCode: 'Код проверки мобильного телефона',
      verificationCode: 'Код проверки',
      rulesusername: 'Заполните имя пользователя.',
      rulespassword: 'Заполните пароль.',
      'zheng-zai-jia-zai-xi-tong-zhong': 'Загружается в систему....',
      rulesphonenumber: 'Пожалуйста, введите правильный номер телефона.',
      Integratedaccount: 'Интегрированный аккаунт, вход запрещен',
      Usernamecannotempty: 'Имя пользователя не может быть пустым',
      phonenumberempty: 'Номер телефона не может быть пустым.',
      Sendverificationcode: 'Отправить код проверки',
      Verificamobile: 'Проверка мобильного телефона',
      Verificationcodesentsuccessfully: 'Код проверки успешно отправлен',
      Verificationcodesenterrorfully: 'Ошибка отправки кода проверки',
      forgotpassword: 'Забыть пароль?',
      Resendinseconds: 'Повторная отправка через секунду.',
      ElectronicCatalogPublishingSystem: 'Электронная каталоговая система',
      Welcometologin: 'Добро пожаловать на посадку.',
      Customersatisfaction: 'Клиенты довольны',
      Itisourmission: 'Это наша цель.',
      'Responsibility/Communication/Inclusiveness': 'Ответственность / коммуникация / инклюзивность',
      Retrievepassword: 'Вернуть пароль',
      Pleaseenteryourphonenumber: 'Пожалуйста, введите номер телефона.',
      Pleaseentertheverificationcode: 'Введите код проверки.',
      Volveraenviardespuésdesegundos: 'Повторная отправка через секунду.',
      Password: 'Новый пароль',
      Confirmpassword: 'Подтвердить пароль',
      Thenewpasswordcannotbeempty: 'Новый пароль не может быть пустым',
      Confirmpasswordcannotbeempty: 'Пароль подтверждения не может быть пустым',
      Modifiedsuccessfully: 'Изменение успешно',
      Thepasswordenteredtwicemustbeconsistent: 'Пароль должен совпадать дважды.',
      sure: 'Определение',
      Cancelación: 'Отменить',
      PasswordPrompt:
        'Пароль должен содержать четыре формальных текста: заглавные буквы, строчные буквы, цифры и специальные символы: пароль не может содержать: непрерывные буквы, цифры или символы клавиатуры, повторяющиеся буквы или цифры, рабочий номер, номер счета OA, полное имя, инициалы имени, номер телефона: день рождения и другие общие пароли или пароли по умолчанию.',
    },
  ];
  // 法语
  const arrfrFR = [
    {
      'deng-lu': 'Se connecter',
      tenantName: 'Nom du locataire',
      username: 'Nom dutilisateur',
      password: 'Mot de passe',
      phoneNumber: 'Numéro de téléphone portable',
      phoneCode: 'Code de vérification du téléphone portable',
      verificationCode: 'Code de vérification',
      rulesusername: 'Veuillez remplir le nom dutilisateur',
      rulespassword: 'Veuillez remplir le mot de passe',
      'zheng-zai-jia-zai-xi-tong-zhong': 'Chargement dans le système....',
      rulesphonenumber: 'Veuillez entrer le bon numéro de téléphone portable',
      Integratedaccount: 'Numéro de compte intégré, connexion interdite',
      Usernamecannotempty: 'Имя пользователя не может быть пустым',
      phonenumberempty: 'Le numéro de téléphone portable ne peut pas être vide',
      Sendverificationcode: 'Envoyer le Code de vérification',
      Verificamobile: 'Vérification du téléphone portable',
      Verificationcodesentsuccessfully: 'CAPTCHA envoyé avec succès',
      Verificationcodesenterrorfully: 'Lenvoi du CAPTCHA a échoué',
      forgotpassword: 'Mot de passe oublié?',
      Resendinseconds: 'Renvoyer en secondes',
      ElectronicCatalogPublishingSystem: ' accessoires système de catalogue électronique',
      Welcometologin: 'Bienvenue au débarquement',
      Customersatisfaction: 'Satisfaction du client',
      Itisourmission: 'Est notre but',
      'Responsibility/Communication/Inclusiveness': 'Responsabilité / communication / inclusion',
      Retrievepassword: 'Récupérer le mot de passe',
      Pleaseenteryourphonenumber: 'Veuillez entrer un numéro de téléphone portable',
      Pleaseentertheverificationcode: 'Veuillez entrer le Code de vérification',
      Volveraenviardespuésdesegundos: 'Renvoyer en secondes',
      Password: 'Nouveau mot de passe',
      Confirmpassword: 'Confirmer le mot de passe',
      Thenewpasswordcannotbeempty: 'Le nouveau mot de passe ne peut pas être vide',
      Confirmpasswordcannotbeempty: 'Confirmer le mot de passe ne peut pas être vide',
      Modifiedsuccessfully: 'Modification réussie',
      Thepasswordenteredtwicemustbeconsistent: 'Le mot de passe saisi deux fois doit être cohérent',
      sure: 'Déterminer',
      Cancelación: 'Annulation',
      PasswordPrompt:
        'Le mot de passe doit contenir 4 formes de texte: majuscules, minuscules, chiffres et caractères spéciaux: il ne peut pas contenir dans le mot de passe: des lettres continues, des chiffres ou des symboles clavier, des lettres ou des chiffres répétitifs, des numéros de travail, des numéros de compte OA, des épellations complètes de noms, des acronymes, des numéros de téléphone: des mots de passe courants ou des mots de passe par défaut tels que les anniversaires.',
    },
  ];
  // 意大利
  const arritIT = [
    {
      'deng-lu': 'Accedi',
      tenantName: 'Nome dellaffittuario',
      username: 'nome utente',
      password: 'password',
      phoneNumber: 'numero di telefono',
      phoneCode: 'Codice di verifica mobile',
      verificationCode: 'Codice di verifica',
      rulesusername: 'Inserisci il tuo nome utente',
      rulespassword: 'Inserisci la password',
      'zheng-zai-jia-zai-xi-tong-zhong': 'Caricamento nel sistema....',
      rulesphonenumber: 'Inserisci il numero di telefono corretto',
      Integratedaccount: 'Account integrato, accesso vietato',
      Usernamecannotempty: 'Il nome utente non può essere vuoto',
      phonenumberempty: 'Il numero di cellulare non può essere vuoto',
      Sendverificationcode: 'Invia codice di verifica',
      Verificamobile: 'Verifica mobile',
      Verificationcodesentsuccessfully: 'Codice di verifica inviato correttamente',
      Verificationcodesenterrorfully: 'Invio del codice di verifica non riuscito',
      forgotpassword: 'Password dimenticata?',
      Resendinseconds: 'Riinvia in pochi secondi',
      ElectronicCatalogPublishingSystem: ' Parts Electronic Catalog System',
      Welcometologin: 'Benvenuti',
      Customersatisfaction: 'Soddisfazione del cliente',
      Itisourmission: 'È la nostra missione',
      'Responsibility/Communication/Inclusiveness': 'Responsabilità/Comunicazione/Inclusività',
      Retrievepassword: 'Recupera password',
      Pleaseenteryourphonenumber: 'Inserisci il tuo numero di telefono',
      Pleaseentertheverificationcode: 'Inserisci il codice di verifica',
      Volveraenviardespuésdesegundos: 'Ripristina in secondi',
      Password: 'Password',
      Confirmpassword: 'Conferma password',
      Thenewpasswordcannotbeempty: 'La nuova password non può essere vuota',
      Confirmpasswordcannotbeempty: 'Conferma la password non può essere vuota',
      Modifiedsuccessfully: 'Modificato con successo',
      Thepasswordenteredtwicemustbeconsistent: 'La password inserita due volte deve essere coerente',
      sure: 'sicuro',
      Cancelación: 'annulla',
      PasswordPrompt:
        'La password deve contenere quattro forme di testo: lettere maiuscole, minuscole, numeri e caratteri speciali. La password non può contenere lettere consecutive, numeri o simboli di tastiera, lettere o numeri ripetuti, ID dipendente, account OA, nome ortografico completo, iniziali, numero di telefono, compleanno e altre password comuni o predefinite.',
    },
  ];
  // 西班牙
  const arresES = [
    {
      'deng-lu': 'Iniciar sesión',
      tenantName: 'Nombre del inquilino',
      username: 'Nombre de usuario',
      password: 'Contraseña',
      phoneNumber: 'Número de teléfono móvil',
      phoneCode: 'Código de verificación del teléfono móvil',
      verificationCode: 'Código de verificación',
      rulesusername: 'Por favor, rellene el nombre de usuario',
      rulespassword: 'Por favor, rellene la contraseña',
      'zheng-zai-jia-zai-xi-tong-zhong': 'Se está cargando el sistema....',
      rulesphonenumber: 'Introduzca el número de teléfono correcto',
      Integratedaccount: 'Cuenta integrada, prohibido iniciar sesión',
      Usernamecannotempty: 'El nombre del usuario no puede estar vacío',
      phonenumberempty: 'El número de teléfono móvil no puede estar vacío',
      Sendverificationcode: 'Invia codice di verifica',
      Verificamobile: 'Verificación del teléfono móvil',
      Verificationcodesentsuccessfully: 'El Código de verificación fue enviado con éxito.',
      Verificationcodesenterrorfully: 'Falló el envío del Código de verificación',
      forgotpassword: 'Olvida la contraseña?',
      Resendinseconds: 'Volver a enviar después de segundos',
      ElectronicCatalogPublishingSystem: 'Sistema de catálogo electrónico de accesorios ',
      Welcometologin: 'Bienvenido al desembarco',
      Customersatisfaction: 'Satisfacción del cliente',
      Itisourmission: 'Es nuestro propósito.',
      'Responsibility/Communication/Inclusiveness': 'Responsabilidad / comunicación / inclusión',
      Retrievepassword: 'Recuperar la contraseña',
      Pleaseenteryourphonenumber: 'Por favor, introduzca el número de teléfono móvil',
      Pleaseentertheverificationcode: 'Por favor, introduzca el Código de verificación',
      Volveraenviardespuésdesegundos: 'Volver a enviar después de segundos',
      Password: 'Nueva contraseña',
      Confirmpassword: 'Confirmar contraseña',
      Thenewpasswordcannotbeempty: 'La nueva contraseña no puede estar vacía',
      Confirmpasswordcannotbeempty: 'La contraseña de confirmación no puede estar vacía',
      Modifiedsuccessfully: 'Modificación exitosa',
      Thepasswordenteredtwicemustbeconsistent: 'La contraseña introducida dos veces debe ser la misma',
      sure: 'Determinar',
      Cancelación: 'Cancelación',
      PasswordPrompt:
        'La contraseña debe contener cuatro formatos: mayúsculas, minúsculas, números y caracteres especiales: la contraseña no puede contener: letras continuas, números o símbolos de teclado, letras o números duplicados, números de trabajo, cuentas oa, nombre completo, siglas de nombre, número de teléfono: cumpleaños y otras contraseñas comunes o predeterminadas.',
    },
  ];
  if (langtype === 'zh-CN') {
    str = arrzhCN[0][lang];
  } else if (langtype === 'en') {
    str = arrenus[0][lang];
  } else if (langtype === 'ru') {
    str = arrruRU[0][lang];
  } else if (langtype === 'fr') {
    str = arrfrFR[0][lang];
  } else if (langtype === 'it') {
    str = arritIT[0][lang];
  } else if (langtype === 'es') {
    str = arresES[0][lang];
  } else {
    str = arrenus[0][lang];
  }

  return str;
}
