import type { BaseUISchema, BaseUISchemaGetter } from '@wei/openapi-codegen/es/src/BaseUISchema';
import { BaseUISchemaComponentType } from '@wei/openapi-codegen/es/src/BaseUISchemaComponent';
import { UserUpdateRequestDTOModel } from '../models/UserUpdateRequestDTOModel';

export const uiSchema: BaseUISchemaGetter<UserUpdateRequestDTOModel> = (model: UserUpdateRequestDTOModel = new UserUpdateRequestDTOModel()) => {
  const schema: BaseUISchema<UserUpdateRequestDTOModel> = {
    schemaName: 'UserUpdateRequestDTO',
    model,
    dataSource: [],
    rules: {
      username: [
        { max: 30, message: '用户账号的最大长度为 30' },
        { min: 3, message: '用户账号的最小长度为 3' },
        { required: true, message: '请填写用户账号' },
      ],
      nickname: [
        { max: 30, message: '用户昵称的最大长度为 30' },
        { min: 0, message: '用户昵称的最小长度为 0' },
        { required: true, message: '请填写用户昵称' },
      ],
      remark: [],
      deptId: [{ required: true, message: '请填写部门ID' }],
      deptCode: [],
      dept2Code: [],
      email: [
        { max: 50, message: '用户邮箱的最大长度为 50' },
        { min: 0, message: '用户邮箱的最小长度为 0' },
      ],
      mobile: [],
      sex: [],
      avatar: [],
      isAd: [],
      workCard: [],
      id: [{ required: true, message: '请填写用户编号' }],
      roleId: [],
    },
    columns: [
      {
        dataIndex: 'username',
        title: '用户账号',
        label: '用户账号',
        name: 'username',
        schemaOriginalDescription: '用户账号',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'nickname',
        title: '用户昵称',
        label: '用户昵称',
        name: 'nickname',
        schemaOriginalDescription: '用户昵称',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'remark',
        title: '备注',
        label: '备注',
        name: 'remark',
        schemaOriginalDescription: '备注',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'deptId',
        title: '部门ID',
        label: '部门ID',
        name: 'deptId',
        schemaOriginalDescription: '部门ID',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'deptCode',
        title: '部门Code',
        label: '部门Code',
        name: 'deptCode',
        schemaOriginalDescription: '部门Code',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'dept2Code',
        title: '部门2Code',
        label: '部门2Code',
        name: 'dept2Code',
        schemaOriginalDescription: '部门2Code',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'email',
        title: '用户邮箱',
        label: '用户邮箱',
        name: 'email',
        schemaOriginalDescription: '用户邮箱',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'mobile',
        title: '手机号码',
        label: '手机号码',
        name: 'mobile',
        schemaOriginalDescription: '手机号码',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'sex',
        title: '用户性别',
        label: '用户性别',
        name: 'sex',
        schemaOriginalDescription: '用户性别，参见 SexEnum 枚举类',
        schemaOption: { schemaType: BaseUISchemaComponentType.InputNumber },
      },
      {
        dataIndex: 'avatar',
        title: '用户头像',
        label: '用户头像',
        name: 'avatar',
        schemaOriginalDescription: '用户头像',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'isAd',
        title: '是否AD域验证',
        label: '是否AD域验证',
        name: 'isAd',
        schemaOriginalDescription: '是否AD域验证',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'workCard',
        title: '工号',
        label: '工号',
        name: 'workCard',
        schemaOriginalDescription: '工号',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'id',
        title: '用户编号',
        label: '用户编号',
        name: 'id',
        schemaOriginalDescription: '用户编号',
        schemaOption: { schemaType: BaseUISchemaComponentType.InputNumber },
      },
      {
        dataIndex: 'roleId',
        title: '角色ID',
        label: '角色ID',
        name: 'roleId',
        schemaOriginalDescription: '角色ID',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
    ],
    schemaData: {
      required: ['deptId', 'id', 'nickname', 'username'],
      type: 'object',
      properties: {
        username: {
          maxLength: 30,
          minLength: 3,
          type: 'string',
          description: '用户账号',
          example: '',
        },
        nickname: {
          maxLength: 30,
          minLength: 0,
          type: 'string',
          description: '用户昵称',
          example: '',
        },
        remark: { type: 'string', description: '备注', example: '我是一个用户' },
        deptId: { type: 'string', description: '部门ID', example: '我是一个部门' },
        deptCode: { type: 'string', description: '部门Code', example: '我是一个部门Code' },
        dept2Code: { type: 'string', description: '部门2Code', example: '我是一个部门Code' },
        email: {
          maxLength: 50,
          minLength: 0,
          type: 'string',
          description: '用户邮箱',
          example: '',
        },
        mobile: { type: 'string', description: '手机号码', example: '15601691300' },
        sex: {
          type: 'integer',
          description: '用户性别，参见 SexEnum 枚举类',
          format: 'int32',
          example: 1,
        },
        avatar: {
          type: 'string',
          description: '用户头像',
          example: 'https://www.iocoder.cn/xxx.png',
        },
        isAd: { type: 'string', description: '是否AD域验证', example: '0' },
        workCard: { type: 'string', description: '工号', example: '1041245' },
        id: {
          type: 'integer',
          description: '用户编号',
          format: 'int64',
          example: 1024,
        },
        roleId: { type: 'string', description: '角色ID' },
      },
      description: '管理后台 - 用户更新 Request DTO',
    },
  };
  return schema;
};

export default uiSchema;
