import type { BaseUISchema, BaseUISchemaGetter } from '@wei/openapi-codegen/es/src/BaseUISchema';
import { BaseUISchemaComponentType } from '@wei/openapi-codegen/es/src/BaseUISchemaComponent';
import { UserPageItemResponseDTOModel } from '../models/UserPageItemResponseDTOModel';
import { SystemUserSexDict } from '@/dictionaries/SystemUserSex';

export const uiSchema: BaseUISchemaGetter<UserPageItemResponseDTOModel> = (model: UserPageItemResponseDTOModel = new UserPageItemResponseDTOModel()) => {
  const schema: BaseUISchema<UserPageItemResponseDTOModel> = {
    schemaName: 'UserPageItemResponseDTO',
    model,
    dataSource: [],
    rules: {
      username: [
        { max: 30, message: '用户账号的最大长度为 30' },
        { min: 3, message: '用户账号的最小长度为 3' },
        { required: true, message: '请填写用户账号' },
      ],
      nickname: [
        { max: 30, message: '用户昵称的最大长度为 30' },
        { min: 0, message: '用户昵称的最小长度为 0' },
        { required: true, message: '请填写用户昵称' },
      ],
      remark: [],
      deptId: [{ required: true, message: '请填写部门ID' }],
      deptCode: [],
      dept2Code: [],
      email: [
        { max: 50, message: '用户邮箱的最大长度为 50' },
        { min: 0, message: '用户邮箱的最小长度为 0' },
      ],
      mobile: [],
      sex: [],
      avatar: [],
      isAd: [],
      workCard: [],
      id: [{ required: true, message: '请填写用户编号' }],
      status: [{ required: true, message: '请填写状态' }],
      loginIp: [{ required: true, message: '请填写最后登录 IP' }],
      loginDate: [{ required: true, message: '请填写最后登录时间' }],
      createTime: [{ required: true, message: '请填写创建时间' }],
      dept: [],
      depts: [],
    },
    columns: [
      {
        dataIndex: 'username',
        title: '用户账号',
        label: '用户账号',
        name: 'username',
        schemaOriginalDescription: '用户账号',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'nickname',
        title: '用户昵称',
        label: '用户昵称',
        name: 'nickname',
        schemaOriginalDescription: '用户昵称',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'remark',
        title: '备注',
        label: '备注',
        name: 'remark',
        schemaOriginalDescription: '备注',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'deptId',
        title: '部门ID',
        label: '部门ID',
        name: 'deptId',
        schemaOriginalDescription: '部门ID',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'deptCode',
        title: '部门Code',
        label: '部门Code',
        name: 'deptCode',
        schemaOriginalDescription: '部门Code',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'dept2Code',
        title: '部门2Code',
        label: '部门2Code',
        name: 'dept2Code',
        schemaOriginalDescription: '部门2Code',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'email',
        title: '用户邮箱',
        label: '用户邮箱',
        name: 'email',
        schemaOriginalDescription: '用户邮箱',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'mobile',
        title: '手机号码',
        label: '手机号码',
        name: 'mobile',
        schemaOriginalDescription: '手机号码',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'sex',
        title: '用户性别',
        label: '用户性别',
        name: 'sex',
        schemaOriginalDescription: '用户性别，参见 SexEnum 枚举类',
        schemaOption: { schemaType: BaseUISchemaComponentType.Radio, options: SystemUserSexDict.items },
      },
      {
        dataIndex: 'avatar',
        title: '用户头像',
        label: '用户头像',
        name: 'avatar',
        schemaOriginalDescription: '用户头像',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'isAd',
        title: '是否AD域验证',
        label: '是否AD域验证',
        name: 'isAd',
        schemaOriginalDescription: '是否AD域验证',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'workCard',
        title: '工号',
        label: '工号',
        name: 'workCard',
        schemaOriginalDescription: '工号',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'id',
        title: '用户编号',
        label: '用户编号',
        name: 'id',
        schemaOriginalDescription: '用户编号',
        schemaOption: { schemaType: BaseUISchemaComponentType.InputNumber },
      },
      {
        dataIndex: 'status',
        title: '状态',
        label: '状态',
        name: 'status',
        schemaOriginalDescription: '状态，参见 CommonStatusEnum 枚举类',
        schemaOption: { schemaType: BaseUISchemaComponentType.InputNumber },
      },
      {
        dataIndex: 'loginIp',
        title: '最后登录 IP',
        label: '最后登录 IP',
        name: 'loginIp',
        schemaOriginalDescription: '最后登录 IP',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'loginDate',
        title: '最后登录时间',
        label: '最后登录时间',
        name: 'loginDate',
        schemaOriginalDescription: '最后登录时间',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'createTime',
        title: '创建时间',
        label: '创建时间',
        name: 'createTime',
        schemaOriginalDescription: '创建时间',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'dept',
        title: '部门',
        label: '部门',
        name: 'dept',
        schemaOriginalDescription: '部门',
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
      {
        dataIndex: 'depts',
        title: 'depts',
        label: 'depts',
        name: 'depts',
        schemaOriginalDescription: undefined,
        schemaOption: { schemaType: BaseUISchemaComponentType.Input },
      },
    ],
    schemaData: {
      required: ['createTime', 'deptId', 'id', 'loginDate', 'loginIp', 'nickname', 'status', 'username'],
      type: 'object',
      properties: {
        username: {
          maxLength: 30,
          minLength: 3,
          type: 'string',
          description: '用户账号',
          example: '',
        },
        nickname: {
          maxLength: 30,
          minLength: 0,
          type: 'string',
          description: '用户昵称',
          example: '',
        },
        remark: { type: 'string', description: '备注', example: '我是一个用户' },
        deptId: { type: 'string', description: '部门ID', example: '我是一个部门' },
        deptCode: { type: 'string', description: '部门Code', example: '我是一个部门Code' },
        dept2Code: { type: 'string', description: '部门2Code', example: '我是一个部门Code' },
        email: {
          maxLength: 50,
          minLength: 0,
          type: 'string',
          description: '用户邮箱',
          example: '',
        },
        mobile: { type: 'string', description: '手机号码', example: '15601691300' },
        sex: {
          type: 'integer',
          description: '用户性别，参见 SexEnum 枚举类',
          format: 'int32',
          example: 1,
        },
        avatar: {
          type: 'string',
          description: '用户头像',
          example: 'https://www.iocoder.cn/xxx.png',
        },
        isAd: { type: 'string', description: '是否AD域验证', example: '0' },
        workCard: { type: 'string', description: '工号', example: '1041245' },
        id: {
          type: 'integer',
          description: '用户编号',
          format: 'int64',
          example: 1,
        },
        status: {
          type: 'integer',
          description: '状态，参见 CommonStatusEnum 枚举类',
          format: 'int32',
          example: 1,
        },
        loginIp: {
          type: 'string',
          description: '最后登录 IP',
          example: '192.168.1.1',
        },
        loginDate: { type: 'string', description: '最后登录时间', format: 'date-time' },
        createTime: { type: 'string', description: '创建时间', format: 'date-time' },
        dept: {
          required: ['id', 'name'],
          type: 'object',
          properties: {
            id: {
              type: 'integer',
              description: '部门编号',
              format: 'int64',
              example: 1,
            },
            name: { type: 'string', description: '部门名称', example: '研发部' },
          },
          description: '部门',
        },
        depts: {
          type: 'array',
          items: {
            required: ['id', 'name'],
            type: 'object',
            properties: {
              id: {
                type: 'integer',
                description: '部门编号',
                format: 'int64',
                example: 1,
              },
              name: { type: 'string', description: '部门名称', example: '研发部' },
            },
            description: '部门',
          },
        },
      },
      description: '管理后台 - 用户分页时的信息 Response DTO，相比用户基本信息来说，会多部门信息',
    },
  };
  return schema;
};

export default uiSchema;
