import type { CabinetAssemblyTableRow, Page5_6ParameterItem } from './types';

function createDefaultAssemblyRow(): CabinetAssemblyTableRow {
  return {
    p0: '1',
    cellParameterId0: '',
    cellParentNum0: '',
    cellInputOrOutput0: '1',
    parameterNum0: '',
    cellInputName0: '序号',
    p1: 1,
    cellParameterId1: '',
    cellParentNum1: '',
    cellInputOrOutput1: '1',
    parameterNum1: '',
    cellInputName1: '类别',
    p2: '',
    cellParameterId2: '',
    cellParentNum2: '',
    cellInputOrOutput2: '1',
    cellInputName2: '模型文件名',
    parameterNum2: '',
    cellParaType2: '',
    p3: '',
    cellParameterId3: '',
    cellParentNum3: '',
    cellInputOrOutput3: '1',
    cellInputName3: '插箱名称',
    parameterNum3: '',
    cellParaType3: '',
    p4: '',
    cellParameterId4: '',
    cellParentNum4: '',
    cellInputOrOutput4: '1',
    cellInputName4: '高度(U)',
    parameterNum4: 'DY4_100_002_U',
    cellParaType4: '',
    p5: '',
    cellParameterId5: '',
    cellParentNum5: '',
    cellInputOrOutput5: '1',
    cellInputName5: '深度',
    parameterNum5: 'DY4_100_002_W',
    cellParaType5: '',
    p6: '',
    cellParameterId6: '',
    cellParentNum6: '',
    cellInputOrOutput6: '1',
    cellInputName6: '宽度',
    parameterNum6: 'DY4_100_002_L',
    cellParaType6: '',
    p7: '',
    cellParameterId7: '',
    cellParentNum7: '',
    cellInputOrOutput7: '1',
    cellInputName7: '新模型文件名',
    p8: 'temp_dy4_100_002.prt',
    cellParameterId8: '',
    cellParentNum8: '',
    cellInputOrOutput8: '1',
    cellInputName8: '模板模型文件名',
    p9: '',
    cellParameterId9: '',
    cellParentNum9: '',
    cellInputOrOutput9: '1',
    cellInputName9: '把手长',
    parameterNum9: 'DY4_100_002_BL',
    cellParaType9: '',
    p10: '',
    cellParameterId10: '',
    cellParentNum10: '',
    cellInputOrOutput10: '1',
    cellInputName10: '定位套间距',
    parameterNum10: 'DY4_100_002_J',
    cellParaType10: '',
    p11: '',
    cellParameterId11: '',
    cellParentNum11: '',
    cellInputOrOutput11: '1',
    cellInputName11: '输入电压V',
    parameterNum11: 'DY_C014_SRDY',
    cellParaType11: '',
    p12: '',
    cellParameterId12: '',
    cellParentNum12: '',
    cellInputOrOutput12: '1',
    cellInputName12: '输出电压V',
    parameterNum12: 'DY_C014_SCDY',
    cellParaType12: '',
    p13: '',
    cellParameterId13: '',
    cellParentNum13: '',
    cellInputOrOutput13: '1',
    cellInputName13: '输出电流A',
    parameterNum13: 'DY_C014_SCDL',
    cellParaType13: '',
    p14: '',
    cellParameterId14: '',
    cellParentNum14: '',
    cellInputOrOutput14: '1',
    cellInputName14: '备注',
    parameterNum14: 'DY_C014_CXBZ',
    cellParaType14: '',
  };
}

function createTableItem(pageid: string, tableNum: string): Page5_6ParameterItem {
  return {
    inputType: 'table',
    ifSingleLine: 't',
    pageId: pageid,
    tableMap: {
      tableType: '2',
      colNums: '9',
      rowData: [createDefaultAssemblyRow()],
      colStr: ['p0', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14'],
    },
    tableName: '装配组合',
    inputName: '',
    tableType: '2',
    tableNum,
  };
}

export function initCustomizedProcessPage7Data5_6(pageid: string): Page5_6ParameterItem[] {
  return [
    createTableItem(pageid, 'DY1-6-2_3_T_ZPZH_1'),
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DY1_1_10_NUM',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId: pageid,
      inputName: '电源机柜数量',
    },
    createTableItem(pageid, 'DY1-6-2_3_T_ZPZH_2'),
    createTableItem(pageid, 'DY1-6-2_3_T_ZPZH_3'),
    createTableItem(pageid, 'DY1-6-2_3_T_ZPZH_4'),
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DY1_6_2_SCDLH',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId: pageid,
      inputName: '输出电流A(求和)',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DY1_6_2_SCDLH_2',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId: pageid,
      inputName: '输出电流A(求和)',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DY1_6_2_SCDLH_3',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId: pageid,
      inputName: '输出电流A(求和)',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DY1_6_2_SCDLH_4',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId: pageid,
      inputName: '输出电流A(求和)',
    },
  ];
}

export function cloneParameterList(source: Page5_6ParameterItem[]): Page5_6ParameterItem[] {
  return JSON.parse(JSON.stringify(source)) as Page5_6ParameterItem[];
}

export type { CabinetAssemblyTableRow, Page5_6ParameterItem };
