export interface Page1_4ParameterItem {
  inputOrOutput?: string;
  ifSingleLine?: string;
  inputType?: string;
  parameterNum?: string;
  parameterId?: string;
  defaultValue?: string;
  propertyType?: string;
  pageId?: string;
  inputName?: string;
  id?: string | number;
  tableMap?: {
    colNums?: string | number;
    rowData?: Array<Record<string, string>>;
  };
}

export function createDefaultPage1_4ParameterList(pageId = ''): Page1_4ParameterItem[] {
  return [
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'DJ1_1_GZFS',
      parameterId: '',
      defaultValue: '',
      pageId,
      inputName: '舟它工作方式',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_SCLJ_MAX_X',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '舟它最大输出力矩',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_SCLJ_ED_X',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '额定输出力矩',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_FZZS_X',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '舟它负载转速（旋转）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_JXXC_X',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '机械行程（单边转角）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_KZZS_MAX_X',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '最大空载转速（旋转）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_EDGL_X',
      parameterId: '192',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '舟它额定功率（旋转）',
    },
    {
      inputOrOutput: '0',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ2_0_CDXL',
      parameterId: '',
      defaultValue: '0.75',
      propertyType: '1',
      pageId,
      inputName: '传动效率',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_5_DXLB',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '等效力臂',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '1',
      parameterNum: 'DJ1_5_MDJSQXS',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '舟它末端减速器形式',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_5_JSQZH_Z',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '减速器载荷（直线）（N）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_5_JSQZH_X',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '减速器载荷（旋转）（Nm）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_SCL_MAX_Z',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '舟它最大输出力',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_SCL_ED_Z',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '额定输出力',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_FZZS_Z',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '舟它负载转速（直线）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_JXXC_Z',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '机械行程（单边直线）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_KZZS_MAX_Z',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '最大空载转速（直线）',
    },
    {
      inputOrOutput: '1',
      ifSingleLine: '1',
      inputType: '0',
      parameterNum: 'DJ1_1_EDGL_Z',
      parameterId: '',
      defaultValue: '',
      propertyType: '1',
      pageId,
      inputName: '舟它额定功率（直线）',
    },
  ];
}
